version: "3.8"
services:
  db:
    image: postgres:15
    container_name: relatorios-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_PROD}
      POSTGRES_USER: ${POSTGRES_USER_PROD}
      POSTGRES_PASSWORD: ${POSTGRES_PASS_PROD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: relatorios-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8081"
    volumes:
      - reports_data:/app-data/reports
    restart: always
    environment:
      # Adiciona as vari√°veis de ambiente do banco de dados diretamente
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB_PROD}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER_PROD}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASS_PROD}
      - SERVER_PORT=8081
      - SPRING_PROFILES_ACTIVE=prod 
      - JWT_SECRET_KEY=${PROD_JWT_SECRET}

volumes:
  postgres_data:
  reports_data:
